#!/bin/bash

scp index.html favicon.ico drupalga@drupalgap.org:~/www/demo/
scp 8/index.html 8/settings.js drupalga@drupalgap.org:~/www/demo/8/
scp 8/bootstrap/index.html 8/bootstrap/settings.js  drupalga@drupalgap.org:~/www/demo/8/bootstrap/
scp 8/foundation/index.html 8/foundation/settings.js  drupalga@drupalgap.org:~/www/demo/8/foundation/
ssh drupalga@drupalgap.org 'bash -s' < scripts/remote_clear
cd 8/modules/custom/demo
scp -r demo.js demo.min.js demo.css images LICENSE drupalga@drupalgap.org:~/www/demo/8/modules/custom/demo
cd /var/www/html/drupalgap.web/demo
ssh drupalga@drupalgap.org 'bash -s' < scripts/remote_pull
